# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the build branch
on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

 # Update reference-ccda-validator repo used in docker file
  - name: Update reference-ccda-validator  repo
    working-directory: .
    run: cd reference-ccda-validator  && git pull

 # Update content-validator-api repo used in docker file
  - name: Update content-validator-api repo
    working-directory: .
    run: cd content-validator-api && git pull

 # Update code-validator-api repo used in docker file
  - name: Update code-validator-api repo
    working-directory: .
    run: cd code-validator-api && git pull

 # Update 2015-certification-ccda-testdata repo used in docker file
  - name: Update 2015-certification-ccda-testdata repo
    working-directory: .
    run: cd 2015-certification-ccda-testdata && git pull

  - wget:
    runs-on: ubuntu-18.04
    steps:
    - name: wget
      uses: actions/checkout@v2
      with:
        args: -o referenceccdaservice.war https://github.com/onc-healthit/reference-ccda-validator/releases/download/1.0.46/referenceccdaservice.war

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

 # Update reference-ccda-validator repo used in docker file
    - name: Update  reference-ccda-validator repo
      working-directory: .
      run: cd reference-ccda-validator && git pull

 # Update content-validator-api repo used in docker file
    - name: Update content-validator-api repo
      working-directory: .
      run: cd content-validator-api && git pull

 # Update code-validator-api repo used in docker file
    - name: Update code-validator-api repo
      working-directory: .
      run: cd code-validator-api && git pull

 # Update 2015-certification-ccda-testdata repo used in docker file
    - name: Update 2015-certification-ccda-testdata repo
      working-directory: .
      run: cd 2015-certification-ccda-testdata && git pull

#    - name: Get the latest .war file
#      working-directory: .
#      run: wget https://github.com/onc-healthit/reference-ccda-validator/releases/download/1.0.46/referenceccdaservice.war

#    - name: Get the latest .war file
#    - wget:  Get the latest .war file
#          steps:
#          - name: wget
#            uses: actions/checkout@v2
#            with:
#              args: https://github.com/onc-healthit/reference-ccda-validator/releases/download/1.0.46/referenceccdaservice.war

    # Build out docker container
    - name: build docker container
      run: docker build --tag=validator .

    # Deploy docker container if finished successfully
    - name: Run new image
      run: docker run -d --tag=validator --port 8080z;8080 validator
