# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the build branch
on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build out docker container
    - name: build docker container
      run: docker build --tag=validator .

    # Deploy docker container if finished successfully 
    - name: Run new image
      run: docker run -d --tag=validator --port 8080z;8080 validator
